#!/bin/sh

# show all available tmux windows and connect to one
# see also utils/term/tmxcycle

XTERM=urxvt

if [ "x$TERM" != "xrxvt" -a "x$TERM" != "xscreen" -a "x$TERM" != "xxterm" ] ; then
   exec $XTERM -e tmuxsel
else
   set - $(tmux lsw -a -F '#{window_id}' 2>/dev/null) 
   if [ $# -eq 0 ] ; then
       printf "No tmux sessions were found. Press enter or type a session name to start a new session or CTRL-C to exit."
   else
       printf "The following windows are available, select an index:\n"
       for w ; do
           printf "$((i+=1)) "
           tmux lsw -a -F "#{window_name} #{session_name} #{window_id}" |sed -ne "s/$w$//p"
       done
   fi
   read s
   if expr $s \<= $# \& $s \> 0 >/dev/null 2>&1  ; then
       set - $(tmux lsw -a -F '#{session_name}|#{window_index}')
       shift $(expr $s - 1)
       session_name=${1%|*}
       window_index=${1#*|}
   else
       session_name=$s
   fi
   if which -s tmxcycle ; then
       tmxcycle $session_name $window_index
   elif [ -n "$window_index" ] ; then
       tmux at -t $session_name \; selectw -t $window_index
   else
       tmux new -s $session_name
   fi

fi
